CSS Ecommerce Page - Michael Van Doorn
Michaelvxd/m1-1222-code-solutions pull request #31
Opened 2022-12-31 03:56 UTC by Michaelvxd

<img width="1723" alt="CleanShot 2022-12-30 at 19 56 44@2x" src="https://user-images.githubusercontent.com/76458151/210124103-53a0b1a1-0337-4de3-be42-3cf09775b1a8.png">

2022-12-31 03:58 UTC, Michaelvxd commented on css-ecommerce-page/styles.css
> +  width: 100%;
I feel like there's a better way to make images scale. Am I missing something?

2022-12-31 03:58 UTC, Michaelvxd commented on css-ecommerce-page/styles.css
> +  margin: 0 100px;
Could I set the margins on the left/right of the website in a better manner?

2023-01-03 00:06 UTC, scrumptiousdev commented on css-ecommerce-page/styles.css
> +  margin: 0 100px;
It really depends on website needs — if one of many components / sections needs full width then setting margins on each component (like you can add new style `max-width-1200` class and add it to `row` div whenever it needs the margins on the sides. But on the other hand, if there is no full-width component, then you can set margins on `.container` or `body` itself

2023-01-03 00:08 UTC, scrumptiousdev requested changes

2023-01-03 00:08 UTC, scrumptiousdev commented on css-ecommerce-page/styles.css
> +  width: 100%;
It is not too bad how you have it right now but when you set both image's height and width 100% then it stretches the image — if you take a look a the Louise Vuitton image it's stretched atm. You can either use backgroun-image css or object-fit

2023-01-17 03:54 UTC, Michaelvxd commented on css-ecommerce-page/styles.css
> +  width: 100%;
Updated! Ty

2023-01-17 04:29 UTC, scrumptiousdev approved these changes
Approved!

2023-01-17 04:29 UTC, merged