JavaScript Loops Practice - Michael Van Doorn
Michaelvxd/m1-1222-code-solutions pull request #35
Opened 2023-01-06 05:10 UTC by Michaelvxd

2023-01-06 05:24 UTC, scrumptiousdev requested changes

2023-01-06 05:24 UTC, scrumptiousdev commented on javascript-loops-practice/odd-or-even.js
> +    }
This is totally fine as is since `number[i] % 2` will be always either 0 or non-0. However just as a quick tip, the second `if` statement still gets executed and that's an extra stuff that computer interprets (even though it's a tiny thing). So we either want to check with `else if` or just `else`.

2023-01-06 05:24 UTC, scrumptiousdev commented on javascript-loops-practice/includes-seven.js
> +  return myBoolean;
In this case, we can remove `myBoolean` variable and just return `false` here. Again, it's a tiny thing but extra variable declaration is an extra stuff that gets stored in the computer memory — just tiny details.

2023-01-06 05:36 UTC, Michaelvxd commented on javascript-loops-practice/includes-seven.js
> +  return myBoolean;
🧠 Love the tiny details, updated & thank you!

2023-01-07 02:03 UTC, scrumptiousdev approved these changes
Approved!

2023-01-10 02:28 UTC, merged